// SPDX-License-Identifier: MIT
//! Two-stage instruction decoder for TMS320C28x.
//!
//! Uses lookup tables generated by build.rs for fast pattern matching:
//! 1. Top-byte index narrows candidates to a small group
//! 2. Linear scan within group checks mask/opcode match

use crate::operands::{decode_loc16, decode_loc32};
use crate::types::*;

/// Condition code names (indexed by 4-bit code).
static COND_NAMES: [&str; 16] = [
    "NEQ", "EQ", "GT", "GEQ", "LT", "LEQ", "HI", "HIS", "LO", "LOS", "NOV", "OV", "NTC", "TC",
    "NBIO", "UNC",
];

/// C28x instruction decoder.
pub struct Decoder {
    pub objmode: u32,
}

impl Decoder {
    pub fn new(objmode: u32) -> Self {
        Self { objmode }
    }

    /// Decode a single instruction from raw bytes.
    ///
    /// `data` must be at least 2 bytes. 4 bytes needed for 32-bit instructions.
    /// `addr` is the byte address of the instruction.
    pub fn decode(&self, data: &[u8], addr: u64) -> Option<DecodedInstruction> {
        if data.len() < 2 {
            return None;
        }

        let opcode16 = u16::from_le_bytes([data[0], data[1]]);

        // Stage 1: try 16-bit patterns
        if let Some(insn) = self.try_match(
            opcode16 as u32,
            addr,
            2,
            &INSTRUCTIONS_16,
            &TABLE_16,
            &TABLE_16_INDICES,
            8,
        ) {
            return Some(insn);
        }

        // Stage 2: try 32-bit patterns
        if data.len() < 4 {
            return None;
        }

        // First word → HIGH 16 bits, second word → LOW 16 bits
        let opcode32 = ((data[1] as u32) << 24)
            | ((data[0] as u32) << 16)
            | ((data[3] as u32) << 8)
            | (data[2] as u32);

        self.try_match(
            opcode32,
            addr,
            4,
            &INSTRUCTIONS_32,
            &TABLE_32,
            &TABLE_32_INDICES,
            24,
        )
    }

    fn try_match(
        &self,
        opcode: u32,
        addr: u64,
        size: u8,
        table: &[InstructionDef],
        lookup: &[(u16, u16); 256],
        indices: &[u16],
        shift: u32,
    ) -> Option<DecodedInstruction> {
        let top_byte = ((opcode >> shift) & 0xFF) as usize;
        let (start, count) = lookup[top_byte];
        if count == 0 {
            return None;
        }

        for i in start..(start + count) {
            let idx = indices[i as usize] as usize;
            let def = &table[idx];

            if (opcode & def.mask) != def.opcode {
                continue;
            }
            if let Some(mode) = def.objmode {
                if mode != self.objmode {
                    continue;
                }
            }

            return Some(self.build(def, opcode, addr, size));
        }

        None
    }

    fn build(
        &self,
        def: &InstructionDef,
        opcode: u32,
        addr: u64,
        size: u8,
    ) -> DecodedInstruction {
        let mut operands = Vec::with_capacity(def.operands.len());
        let mut cond_code: Option<u8> = None;

        for op_def in def.operands {
            let op = self.decode_operand(op_def, opcode);
            if op_def.op_type == OpType::Cond4 {
                cond_code = Some(op.value as u8);
            }
            operands.push(op);
        }

        let branch_type = resolve_branch_type(def.sem_type, cond_code);
        let mut branch_target = if branch_type != BranchType::None
            && branch_type != BranchType::Return
            && branch_type != BranchType::Halt
        {
            resolve_target(def, opcode, addr, size)
        } else {
            None
        };

        // Reject branch targets that land strictly inside the current
        // instruction's own bytes. Such targets are produced when bytes that
        // *happen* to match a branch pattern (e.g. `0x56C3FFFF` decoding as
        // `BF GEQ, -1`) are not actually code. Following them puts BN into
        // mid-instruction decode and chains 64 KB of garbage onto the
        // surrounding function. Targets exactly at `addr` (self-loop) or at
        // `addr + size` (fall-through-as-branch) remain valid.
        if let Some(t) = branch_target {
            if t > addr && t < addr + size as u64 {
                branch_target = None;
            }
        }

        DecodedInstruction {
            id: def.id,
            name: def.name,
            full_name: def.full_name,
            size,
            operands,
            opcode,
            branch_type,
            branch_target,
            sem_type: def.sem_type,
        }
    }

    fn decode_operand(&self, op_def: &OperandDef, opcode: u32) -> Operand {
        let raw = extract_bits(opcode, op_def.high_bit, op_def.low_bit);

        match op_def.op_type {
            OpType::Loc16 => {
                let loc = decode_loc16(raw as u8);
                Operand {
                    op_type: OperandType::Loc16,
                    value: raw as i32,
                    name: "",
                    name_owned: Some(loc.text.clone()),
                    size: 2,
                    signed: false,
                    resolved: Some(loc),
                }
            }
            OpType::Loc32 => {
                let loc = decode_loc32(raw as u8);
                Operand {
                    op_type: OperandType::Loc32,
                    value: raw as i32,
                    name: "",
                    name_owned: Some(loc.text.clone()),
                    size: 4,
                    signed: false,
                    resolved: Some(loc),
                }
            }
            OpType::Ax => {
                let name = if raw != 0 { "AH" } else { "AL" };
                Operand {
                    op_type: OperandType::Register,
                    value: raw as i32,
                    name,
                    name_owned: None,
                    size: 2,
                    signed: false,
                    resolved: None,
                }
            }
            OpType::Cond4 => {
                let idx = (raw & 0xF) as usize;
                Operand {
                    op_type: OperandType::Condition,
                    value: raw as i32,
                    name: COND_NAMES[idx],
                    name_owned: None,
                    size: 0,
                    signed: false,
                    resolved: None,
                }
            }
            OpType::Reg3 => {
                let idx = raw & 0x7;
                Operand {
                    op_type: OperandType::Register,
                    value: raw as i32,
                    name: "",
                    name_owned: Some(format!("XAR{}", idx)),
                    size: 4,
                    signed: false,
                    resolved: None,
                }
            }
            OpType::FpuReg => {
                let idx = raw & 0x7;
                Operand {
                    op_type: OperandType::Register,
                    value: raw as i32,
                    name: "",
                    name_owned: Some(format!("R{}H", idx)),
                    size: 4,
                    signed: false,
                    resolved: None,
                }
            }
            // All immediate types
            _ => {
                let value = if op_def.signed {
                    let bits = op_def.high_bit - op_def.low_bit + 1;
                    sign_extend(raw, bits)
                } else {
                    raw as i32
                };
                Operand {
                    op_type: OperandType::Immediate,
                    value,
                    name: "",
                    name_owned: None,
                    size: 2,
                    signed: op_def.signed,
                    resolved: None,
                }
            }
        }
    }
}

/// Determine branch type from semantic type and condition code.
fn resolve_branch_type(sem_type: SemType, cond_code: Option<u8>) -> BranchType {
    match sem_type {
        SemType::Return => BranchType::Return,
        SemType::Call => BranchType::Call,
        SemType::Trap => BranchType::Trap,
        SemType::Halt => BranchType::Halt,
        SemType::Branch => BranchType::Unconditional,
        SemType::CondBranch => {
            if cond_code == Some(0xF) {
                // UNC condition = unconditional
                BranchType::Unconditional
            } else {
                BranchType::ConditionalTrue
            }
        }
        _ => BranchType::None,
    }
}

/// Resolve the branch target address from instruction operands.
fn resolve_target(def: &InstructionDef, opcode: u32, addr: u64, size: u8) -> Option<u64> {
    for op_def in def.operands {
        let raw = extract_bits(opcode, op_def.high_bit, op_def.low_bit);

        match op_def.op_type {
            OpType::Imm22 => {
                // Absolute 22-bit address; convert word addr to byte addr
                return Some((raw as u64) * 2);
            }
            OpType::Imm16 | OpType::Imm8 if op_def.signed => {
                let bits = op_def.high_bit - op_def.low_bit + 1;
                let offset = sign_extend(raw, bits) as i64;
                // PC-relative: next_pc (in words) + offset, then to bytes
                let next_pc_words = (addr / 2) + (size as u64 / 2);
                let target_words = (next_pc_words as i64 + offset) as u64;
                return Some(target_words * 2);
            }
            _ => {}
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_decode_nop() {
        let d = Decoder::new(1);
        let data = [0x00, 0x77, 0x00, 0x00]; // NOP = 0x7700
        let insn = d.decode(&data, 0).unwrap();
        assert_eq!(insn.id, InsnId::NOP);
        assert_eq!(insn.size, 2);
    }

    #[test]
    fn test_decode_nop_zero() {
        let d = Decoder::new(1);
        let data = [0x00, 0x00, 0x00, 0x00]; // NOP_ZERO = 0x0000
        let insn = d.decode(&data, 0).unwrap();
        assert_eq!(insn.id, InsnId::NOP_ZERO);
        assert_eq!(insn.size, 2);
    }

    #[test]
    fn test_decode_lretr() {
        let d = Decoder::new(1);
        let data = [0x06, 0x00, 0x00, 0x00]; // LRETR = 0x0006
        let insn = d.decode(&data, 0).unwrap();
        assert_eq!(insn.id, InsnId::LRETR);
        assert_eq!(insn.branch_type, BranchType::Return);
    }

    #[test]
    fn test_decode_estop0_halt() {
        let d = Decoder::new(1);
        let data = [0x25, 0x76, 0x00, 0x00]; // ESTOP0 = 0x7625
        let insn = d.decode(&data, 0).unwrap();
        assert_eq!(insn.id, InsnId::ESTOP0);
        assert_eq!(insn.branch_type, BranchType::Halt);
        assert_eq!(insn.branch_target, None);
    }

    #[test]
    fn test_decode_estop1_halt() {
        let d = Decoder::new(1);
        let data = [0x24, 0x76, 0x00, 0x00]; // ESTOP1 = 0x7624
        let insn = d.decode(&data, 0).unwrap();
        assert_eq!(insn.id, InsnId::ESTOP1);
        assert_eq!(insn.branch_type, BranchType::Halt);
    }

    #[test]
    fn test_bf_into_self_rejected() {
        // BF GEQ, -1 = 0x56C3FFFF decoded at byte address X.
        // target = (X/2 + 4/2 + (-1)) * 2 = X + 2, which is inside the 4-byte BF.
        // After Phase 3a, branch_target must be None so BN treats it as
        // unresolved (terminates BB without following into mid-instruction).
        let d = Decoder::new(1);
        let bytes = [0xC3, 0x56, 0xFF, 0xFF]; // BF GEQ, -1
        let insn = d.decode(&bytes, 0x1000).unwrap();
        assert_eq!(insn.id, InsnId::BF);
        assert_eq!(insn.branch_type, BranchType::ConditionalTrue);
        assert_eq!(insn.branch_target, None, "BF target must be rejected when it lands inside the instruction");
    }

    #[test]
    fn test_b_into_self_rejected() {
        // B UNC, -1 = bytes producing opcode32 0xFFFFFFFF would match B
        // but the new branch.yaml mask 0xFFF00000 already prevents that.
        // Try B UNC, -1 with valid encoding: 0xFFEF + 0xFFFF.
        // opcode32 = 0xFFEFFFFF, matches B (mask 0xFFF00000 -> opcode 0xFFE00000).
        // target = (X/2 + 2 + (-1)) * 2 = X + 2, mid-instruction.
        let d = Decoder::new(1);
        let bytes = [0xEF, 0xFF, 0xFF, 0xFF]; // B UNC, -1
        let insn = d.decode(&bytes, 0x2000).unwrap();
        assert_eq!(insn.id, InsnId::B);
        assert_eq!(insn.branch_target, None, "B target landing inside instruction must be rejected");
    }

    #[test]
    fn test_branch_to_self_allowed() {
        // SB UNC, -1 at byte X: target = X/2 + 1 + (-1) = X/2 (word) = X byte.
        // target == addr (start of same instruction), NOT strictly inside.
        // This is a legit `while(1){}` self-loop and must be kept.
        let d = Decoder::new(1);
        let bytes = [0xFF, 0x6F, 0x00, 0x00]; // SB UNC, -1
        let insn = d.decode(&bytes, 0x3000).unwrap();
        assert_eq!(insn.id, InsnId::SB);
        assert_eq!(insn.branch_target, Some(0x3000), "self-loop (target == addr) must be preserved");
    }

    #[test]
    fn test_decode_trap_still_soft() {
        let d = Decoder::new(1);
        // TRAP imm5 = 0x0020 | vector; bare TRAP #0 = 0x0020
        let data = [0x20, 0x00, 0x00, 0x00];
        let insn = d.decode(&data, 0).unwrap();
        assert_eq!(insn.branch_type, BranchType::Trap);
    }

    #[test]
    fn test_decode_eallow() {
        let d = Decoder::new(1);
        let data = [0x22, 0x76, 0x00, 0x00]; // EALLOW = 0x7622
        let insn = d.decode(&data, 0).unwrap();
        assert_eq!(insn.id, InsnId::EALLOW);
    }

    #[test]
    fn test_decode_addb_sp() {
        let d = Decoder::new(1);
        // ADDB SP, #5 → opcode 0xFE00 | 5 = 0xFE05
        let data = [0x05, 0xFE, 0x00, 0x00];
        let insn = d.decode(&data, 0).unwrap();
        assert_eq!(insn.id, InsnId::ADDB_SP_CONST7);
        assert_eq!(insn.operands.len(), 1);
        assert_eq!(insn.operands[0].value, 5);
    }

    #[test]
    fn test_decode_lcr() {
        let d = Decoder::new(1);
        // LCR addr22: opcode 0x7640_0000 | addr
        // addr22 = 0x100 (word addr) → byte addr 0x200
        let addr22: u32 = 0x100;
        let op = 0x76400000 | addr22;
        let data = [
            (op >> 16) as u8,
            (op >> 24) as u8,
            op as u8,
            (op >> 8) as u8,
        ];
        let insn = d.decode(&data, 0).unwrap();
        assert_eq!(insn.id, InsnId::LCR);
        assert_eq!(insn.branch_type, BranchType::Call);
        assert_eq!(insn.branch_target, Some(0x200));
    }

    #[test]
    fn test_decode_b_unc() {
        let d = Decoder::new(1);
        // B off16, UNC: opcode 0xFFE0_0000 | (cond << 16) | offset
        // cond = 0xF (UNC), offset = 5 (signed)
        let op: u32 = 0xFFE00000 | (0xF << 16) | 5;
        let data = [
            (op >> 16) as u8,
            (op >> 24) as u8,
            op as u8,
            (op >> 8) as u8,
        ];
        let insn = d.decode(&data, 0).unwrap();
        assert_eq!(insn.id, InsnId::B);
        assert_eq!(insn.branch_type, BranchType::Unconditional);
        // Target: (addr/2 + size/2 + 5) * 2 = (0 + 2 + 5) * 2 = 14
        assert_eq!(insn.branch_target, Some(14));
    }

    #[test]
    fn test_decode_b_cond() {
        let d = Decoder::new(1);
        // B off16, EQ: cond = 0x1
        let op: u32 = 0xFFE00000 | (0x1 << 16) | 3;
        let data = [
            (op >> 16) as u8,
            (op >> 24) as u8,
            op as u8,
            (op >> 8) as u8,
        ];
        let insn = d.decode(&data, 0).unwrap();
        assert_eq!(insn.id, InsnId::B);
        assert_eq!(insn.branch_type, BranchType::ConditionalTrue);
    }

    #[test]
    fn test_extract_bits() {
        assert_eq!(extract_bits(0xABCD, 15, 8), 0xAB);
        assert_eq!(extract_bits(0xABCD, 7, 0), 0xCD);
        assert_eq!(extract_bits(0xABCD, 11, 8), 0xB);
    }

    #[test]
    fn test_sign_extend() {
        assert_eq!(sign_extend(0xFF, 8), -1);
        assert_eq!(sign_extend(0x7F, 8), 127);
        assert_eq!(sign_extend(0x80, 8), -128);
        assert_eq!(sign_extend(5, 8), 5);
    }
}
